### ISSUE TITLE
[FEAT] Supplier Contact: display the execution count of the "email regenerate loop" in a overlay

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#48]
This will show that we can update the value at runtime 

**Notes**: this will be implemented with a hack as bpmn-visualization currently (v0.33.0) doesn't support it.
Remove overlays, then add a new one.

![image](https://user-images.githubusercontent.com/27200110/226670953-934d754e-623b-4eff-a458-79c9a6f3ebc1.png)

**Comment by assynour** [comment]
@tbouffard

Below are my attempts. The edge delay is set to 500.

**1. Multiple overlay styles to mimic the style of the edge**
![overlay-500](https://user-images.githubusercontent.com/67027776/227589073-3e2adb70-bb98-4fb7-9595-1e99425c5caa.gif)

**2 & 3: Only one overlay style that is not changed**

**2.** The following style is used:
```
font: { color: 'white', size: 20 },
fill: { color: 'rgba(0, 0, 255, 0.5)' },
stroke: { color: 'rgba(0, 0, 255, 0.5)', width: 2 }
```
           
![overlay-no-remove-500](https://user-images.githubusercontent.com/67027776/227589249-d10ac786-71bc-46c7-8014-9a8f2e626e01.gif)

**3.** The following style is used:
```
font: { color: 'white', size: 20 },
fill: { color: 'rgba(0, 0, 255, 0.7)' },
stroke: { color: 'rgba(0, 0, 255, 0.7)', width: 2 }
```
![overlay-no-remove-opacity-0 7-500](https://user-images.githubusercontent.com/67027776/227590100-3afe5c22-bda3-46e8-978a-fd25157fdc4b.gif)

**Comment by tbouffard** [comment]
After discussion with @assynour and @csouchet, we decided to implement this issue and choose the option 1 described in https://github.com/process-analytics/bonita-day-demo-2023/issues/48#issuecomment-1483118456
