### ISSUE TITLE
[FEAT] process monitoring: highlight the message icon of the intermediate catch event

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#57]
Currently, the stroke of the icon remains black. This was like this in https://process-analytics.github.io/icpm-demo-2022/

Do some tests to see if the rendering is nicer if we set the stroke color of the message in green.
To be discussed.

**Comment by assynour** [comment]
@tbouffard

**before**

![event-no-fill](https://user-images.githubusercontent.com/67027776/227707450-6027edb3-bada-4257-9376-5099b4c2e833.png)

**stroke = .2rem:**

![event-fill-1rem](https://user-images.githubusercontent.com/67027776/227707510-c0d6dba4-eb49-47f6-95ae-475cac947e7e.png)

**stroke=.1rem**:

![event-fill-2rem](https://user-images.githubusercontent.com/67027776/227707595-6417bfd9-e70b-45a2-beef-fb066b9c03fd.png)

**Comment by tbouffard** [comment]
After discussion with @assynour and @csouchet, we will keep the current design.
Changing the color of the icon is fuzzy.
